### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by bigman73** [nobleclem/jQuery-MultiSelect#10]
Please add bower.json file to the project

**Comment by bigman73** [comment]
{
  "author": "nobleclem",
  "name": "jQuery-MultiSelect",
  "description": "Turn a multiselect list into a nice and easy to use list with checkboxes",
  "main": [
    "jquery.multiselect.js",
    "jquery.multiselect.css"
  ],
  "license": "MIT",
  "authors": [
    "nobleclem"
  ],
  "moduleType": [],
  "keywords": [
    "jquery",
    "MultiSelect",
    "CheckBox"
  ],
  "homepage": "https://github.com/nobleclem/jQuery-MultiSelect",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ]
}

**Comment by nobleclem** [comment]
Thank you for the config.  I am not a bower user but I see why some people rely on it.
