### ISSUE TITLE
Simple multiselect setup

### ISSUE THREAD

**Issue by joshbrekke** [nobleclem/jQuery-MultiSelect#100]
Hi Patrick,

I've download your multiselect component to test out, but I can't seem to get your sample to work.  I think I'm missing some dependency or have something out of out order, but I can't find it.

**Here's what I have in the page:**

<!DOCTYPE html>

<html>
<body>

                    <select name="basic[]" multiple="multiple" class="3col active">
                        <option value="AL">Alabama</option>
                        <option value="AK">Alaska</option>
                        <option value="AZ">Arizona</option>
                        <option value="AR">Arkansas</option>
                        <option value="CA">California</option>
                        <option value="CO">Colorado</option>
                        <option value="CT">Connecticut</option>
                        <option value="DE">Delaware</option>
                        <option value="FL">Florida</option>
                        <option value="GA">Georgia</option>
                        <option value="HI">Hawaii</option>
                        <option value="ID">Idaho</option>
                        <option value="IL">Illinois</option>
                        <option value="IN">Indiana</option>
                        <option value="IA">Iowa</option>
                        <option value="KS">Kansas</option>
                        <option value="KY">Kentucky</option>
                        <option value="LA">Louisiana</option>
                        <option value="ME">Maine</option>
                        <option value="MD">Maryland</option>
                        <option value="MA">Massachusetts</option>
                        <option value="MI">Michigan</option>
                        <option value="MN">Minnesota</option>
                        <option value="MS">Mississippi</option>
                        <option value="MO">Missouri</option>
                        <option value="MT">Montana</option>
                        <option value="NE">Nebraska</option>
                        <option value="NV">Nevada</option>
                        <option value="NH">New Hampshire</option>
                        <option value="NJ">New Jersey</option>
                        <option value="NM">New Mexico</option>
                        <option value="NY">New York</option>
                        <option value="NC">North Carolina</option>
                        <option value="ND">North Dakota</option>
                        <option value="OH">Ohio</option>
                        <option value="OK">Oklahoma</option>
                        <option value="OR">Oregon</option>
                        <option value="PA">Pennsylvania</option>
                        <option value="RI">Rhode Island</option>
                        <option value="SC">South Carolina</option>
                        <option value="SD">South Dakota</option>
                        <option value="TN">Tennessee</option>
                        <option value="TX">Texas</option>
                        <option value="UT">Utah</option>
                        <option value="VT">Vermont</option>
                        <option value="VA">Virginia</option>
                        <option value="WA">Washington</option>
                        <option value="WV">West Virginia</option>
                        <option value="WI">Wisconsin</option>
                        <option value="WY">Wyoming</option>
                    </select>

</body>
<head>
    <link src="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" />
    <link src="https://springstubbe.us/projects/demos/jquery-multiselect/styles/jquery.multiselect.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://springstubbe.us/projects/demos/jquery-multiselect/scripts/jquery.multiselect.js"></script>

    <script>
        $(function () {
            $('select[multiple].active.3col').multiselect({
                columns: 3,
                placeholder: 'Select States',
                search: true,
                searchOptions: {
                    'default': 'Search States'
                },
                selectAll: true
            });
    
        });
    </script>
</head>
</html>

**---------------------------------------------------------------------------------**

Any ideas of what I'm doing wrong?

Thanks.

Josh

**Comment by nobleclem** [comment]
Dumb question but did you include the css jquery.multiselect.css file into the page?

I probably should create a working standalone demo file as part of the repo.  Something to put on my todo list.

**Comment by joshbrekke** [comment]
Weird...  When I copied over the entire page, it excluded the multiselect.css, but when I just add it below, it's fine.  Not sure why github would omit some of the code...

**Here's the script section**

    <link src="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" />
    <link src="https://springstubbe.us/projects/demos/jquery-multiselect/styles/jquery.multiselect.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://springstubbe.us/projects/demos/jquery-multiselect/scripts/jquery.multiselect.js"></script>

    <script>
        $(function () {
            $('select[multiple].active.3col').multiselect({
                columns: 3,
                placeholder: 'Select States',
                search: true,
                searchOptions: {
                    'default': 'Search States'
                },
                selectAll: true
            });
    
        });
    </script>

**Comment by nobleclem** [comment]
your css [link](https://www.w3schools.com/Tags/tag_link.asp) tags are incorrect.  You are using the attribute "src" instead of "href".

**Comment by joshbrekke** [comment]
That did it. Thanks for pointing that out Patrick!
