### ISSUE TITLE
Loading data from AJAX call

### ISSUE THREAD

**Issue by joshbrekke** [nobleclem/jQuery-MultiSelect#101]
Hi Patrick,

I'm performing an AJAX call to get a list of name/value pairs.  When I pass that list into the multiselect object, nothing seems to happen.  However, if I paste the name/value pairs in the JavaScript file and load the multiselect that way, it loads fine.  Is there some other method call I need to perform after the AJAX call to get the data to appear?

BTW, the JSON data is encapsulated with the [ ] brackets when returned from AJAX (if that helps).

Thanks,

Josh

**Inside the success method of AJAX**
        success: function (data) {
            $('select[id="assignee"]').multiselect('loadOptions', data);
}

**Comment by nobleclem** [comment]
I checked to make sure the loadOptions functionality wasn't broken and it doesn't seem to be at this point.  I am curious as to what your `data` object looks like.

**Comment by joshbrekke** [comment]
**Here's the raw string returned from the AJAX call:**

"[{"name":"user","value":"email"},{"name":"user","value":"email"},{"name":"user","value":"email"},{"name":"user","value":"email"},{"name":"user","value":"email"},{"name":"user","value":"email"},{"name":"user","value":"email"},{"name":"user","value":"email"},{"name":"user","value":"email"},{"name":"user","value":"email"}]"

**Comment by joshbrekke** [comment]
I think it might be the quotes around name & value.

**Comment by nobleclem** [comment]
The quotes should have nothing to do with it.

However I am unable to replicate the problem.  I tested by doing basically this:

```
var data = [{"name":"user","value":"email"},{"name":"user","value":"email2"},{"name":"user","value":"email3"},{"name":"user","value":"email4"},{"name":"user","value":"email5"},{"name":"user","value":"email6"},{"name":"user","value":"email7"},{"name":"user","value":"email8"},{"name":"user","value":"email9"},{"name":"user","value":"email10"}];

$('select').multiselect('loadOptions', data);
```

And they showed up in the select list.

I am also assuming that before your ajax call you have already initialized the multiselect plugin (even if there are no options in your select list)?

**Comment by joshbrekke** [comment]
Yes.  I initialize the plugin before the AJAX call:

    $('select[id="assignee"]').multiselect({
        maxWidth: 200,
        minHeight: 0,
        search: true,
        texts: {
            placeholder: 'Select Assignee(s)'
        }
    });

**Comment by joshbrekke** [comment]
Hi Patrick,

I figured I needed to convert the return object back to a raw JSON structure which appeared to be the issue.

**So if you making an AJAX call to get the data, the data needs to be parsed back to JSON like:**
        success: function (data) {
            var json = $.parseJSON(data);
            $('select[id="assignee"]').multiselect('loadOptions', json);
        }

Thanks for looking at it!

~ Josh
