### ISSUE TITLE
reload option without reset value of multiselect

### ISSUE THREAD

**Issue by kameni98** [nobleclem/jQuery-MultiSelect#102]
hello i want reload other option without reset the actual value of multiselect
`$('#multiselect').multiselect( 'loadOptions', data.responseJSON.data);`

**Comment by nobleclem** [comment]
Are you wanting to just add new options to the list or replace the options?  If you are replacing the options as in your example but want to maintain the value and its not doing that, then I would:

1. Get the value of the multiselect
2. Load the new options (as you are doing in your example)
3. Set the value of the multiselect to what you got in step 1
4. Reload the multiselect plugin `$('select[multiple]').multiselect( 'reload' );`

Alternatively when you perform the loadOptions with your new data, your data object can define what items are checked.

**Comment by jagan27101986** [comment]
I would like to know how to extract selected value from the Multiselect and also while loading i want all the values to be selected in the checkbox , 
Also on onOptionClick i am getting the input type as checkbox however how do i know whether my input is selected or not to extract the values.

Your immediate response would be helpful
