### ISSUE TITLE
Retrieve Values from Jquery 

### ISSUE THREAD

**Issue by jagan27101986** [nobleclem/jQuery-MultiSelect#103]
I would like to know how to extract selected value - checked data from the Multiselect and also while loading i want ALL the values to be selected in the checkbox ,
Also on onOptionClick i am getting the input type as checkbox however how do i know whether my input is selected or not to extract the values.

Your immediate response would be helpful

**Comment by jagan27101986** [comment]
How to select all checkbox on load by default

**Comment by nobleclem** [comment]
See Issues #91 & #81

**Comment by jagan27101986** [comment]
Hi, 
When the screen is loaded , i want all the checkboxes to checked as default with select all. How to achieve that

**Comment by jagan27101986** [comment]
So in the select initially you want to set the selected option as selected ?

**Comment by nobleclem** [comment]
The plugin loads from the select list you are targeting.  So if an option is selected there it will be checked in the plugins dropdown.

**Comment by jagan27101986** [comment]
I want to add the values dynamically to the page onload. How can i do it ?

**Comment by nobleclem** [comment]
From the Usage example in the README.md file

```
$('select[multiple]').multiselect( 'loadOptions', [{
    name   : 'Option Name 1',
    value  : 'option-value-1',
    checked: false,
    attributes : {
        custom1: 'value1',
        custom2: 'value2'
    }
},{
    name   : 'Option Name 2',
    value  : 'option-value-2',
    checked: false,
    attributes : {
        custom1: 'value1',
        custom2: 'value2'
    }
}]);
```

**Comment by jagan27101986** [comment]
I am able to retrieve the values and it is also getting checked. However in the select box i get the text as "17 selected", though there is only one data. Could you please advise how to fix it.
