### ISSUE TITLE
How to identify selected items on page?

### ISSUE THREAD

**Issue by georgich** [nobleclem/jQuery-MultiSelect#106]
Hello!
First, thanks for this plugin! It's really helpful. Second, that is my question. I get items from database, for example:
`$itemsSelected = pdo(SELECT * FROM table)`
This code just for example. And now, how can i use array of itemsSelected to identify selected items in multiselect plugin on my page?
Thank you!

**Comment by nobleclem** [comment]
I am not sure I really understand your question.  This plugin is simply an alternate interface for the native `<select>` list. So if upon page load you want to select items there is no difference than how you normally identify selected items: `<option selected="selected">Option</option>`.

If you are trying to select items after the page is loaded then all you have to do is use normal javascript/jQuery to selected the items: `$('select[multiple]').val( [1, 2, 3] );`  Then trigger a reload using the plugin to pickup the changes to the `<select>` list: `$('select[multiple]').multiselect('reload');`.  I think you could do that in one line as well like `$('select[multiple]').val( [1, 2, 3] ).multiselect('reload');`

**Comment by georgich** [comment]
Oh, thank you for the answer. I try to add `selected="selected"` to the items which is selected.

**Comment by georgich** [comment]
Hello again!
I want to use jQuery to collect selected items. But i observed that when i select items your plugin doesn't add `selected="selected"` to `<option>` element. Plugin make `li` with class selected and `<input>` element into it. How can i choose selected elements with jQuery in your plugin?
Thank you. And sorry for my english :)
