### ISSUE TITLE
is there option to set Maximum Selection option in multiselect dropdown

### ISSUE THREAD

**Issue by dipaksaraf** [nobleclem/jQuery-MultiSelect#107]
Is there option to set a maxselection option a user can choose from multiselect dropdown?

**Comment by nobleclem** [comment]
Right now nothing exists.  However its possible to do using the onOptionClick callback.

You could use it to count the number of selected values and then throw whatever error/warning/notice when a user attempts to select another.  I have not really put much thought into how this would make sense to implement if I were to add it as a feature.
