### ISSUE TITLE
not Working in IE v10, help needed 

### ISSUE THREAD

**Issue by Sumitpd14** [nobleclem/jQuery-MultiSelect#109]
# Need your urgent help on this  nobleclem

* I am trying to use Multiselect js like this 
> $('select[multiple]').multiselect("reset");

* I am trying to reset the check boxes on a button click , it works fine for Chrome  
* When it comes to IE v.10

>line no : 845 from multiselect js 

```javascript
  if( instance instanceof MultiSelect && typeof instance[ options ] === 'function' ) {
         ret = instance[ options ].apply( instance, Array.prototype.slice.call( args, 1 ) );
   }
```
 ```javascript 
            typeof instance[ options ] === 'function'  
  ```   

Returns False

**Comment by nobleclem** [comment]
I tested in IE10 and the reset functionality works just fine.

The only thing I can think of is that maybe you are trying to initialize the plugin like this:
```
$('select[multiple]').multiselect("reset");
```
instead of like this:
```
$('select[multiple]').multiselect();
```
or
```
$('select[multiple]').multiselect({
    columns: 4,
    texts: {
        placeholder: 'Select options'
    }
});
```
