### ISSUE TITLE
Search by group name

### ISSUE THREAD

**Issue by jackyshih** [nobleclem/jQuery-MultiSelect#11]
Hi, 
If it is possible to search the group?
e.g. if i enter "Server-side scripting" in the search bar, it shows all programming languages under that category for me to choose?

**Comment by jackyshih** [comment]
i updated the script to make it support search the group, let me know if you want that, i can share it out

**Comment by nobleclem** [comment]
I would be interested in how you are trying to use this.  I understand what you are trying to do but more why.  I almost feel like if you have too many items that maybe a single select list with individually searchable groups might be too much for users to understand.  But I could be misunderstanding the intent.
