### ISSUE TITLE
Input have the same styles for placeholder and selected state

### ISSUE THREAD

**Issue by alexprey** [nobleclem/jQuery-MultiSelect#112]
At now the button text have the same styles for placeholder and selected items. This is no good, because for all controls it have the different styles (f.ex. placeholder have more lighten color of the text than main text color).
It should be good if new css class for button placeholder state will be introduced.

**Comment by nobleclem** [comment]
a new style "ms-has-selections" will be added to the "ms-options-wrap" element when there are options selected.
