### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by NormySan** [nobleclem/jQuery-MultiSelect#119]
Hey,

I noticed that the project has a package.json file but is not published to NPM. It would br great if you could publish this package to NPM so that it's easier to install with tools like NPM and Yarn.

I also had a quick look at some of the configuration and noticed some errors.

1. The name of the package in package.json, it should be lowercase.
2. The main attribute should be a string pointing to the jquery.multiselect.js file and not both the js and css.
3. You should probably include a peer dependency on the jQuery library.

You can read more about how to configure the package.json file at the following URL.
https://docs.npmjs.com/files/package.json

You can read more about publishing packages to NPM at the following URL.
https://docs.npmjs.com/getting-started/publishing-npm-packages

Best Regards & Happy Holidays

**Comment by nobleclem** [comment]
Published to npm:
https://www.npmjs.com/package/@nobleclem/jquery-multiselect

**Comment by NormySan** [comment]
Awesome, thanks a lot 👍
