### ISSUE TITLE
Is there any option move selected items to the top on button submit

### ISSUE THREAD

**Issue by dotnetmohan** [nobleclem/jQuery-MultiSelect#120]
Because , I have lots value in drop-down list and every time tough to down the scroll  to see the  selected list . So  is there anyway can able to put selected option keep top  on button click .  I have tried this code but no luck.PFB. ,
$("form").on("submit", function (e) {          
        e.preventDefault();
        $("#multiCheck option:selected").prependTo("#multiCheck");
    });

**Comment by nobleclem** [comment]
You might need to trigger a reload in order for the plugin to see the changes.

```$("#multiCheck option:selected").prependTo("#multiCheck").multiselect( 'reload' );```

**Comment by dotnetmohan** [comment]
Woow .. working as expected. Thanks nobeclem
Replaced this way :)
  $("#multiCheck option:selected").prependTo("#multiCheck");
  $("#multiCheck").multiselect( 'reload' );
