### ISSUE TITLE
Can I programmatically select a checkbox?

### ISSUE THREAD

**Issue by Sachelis** [nobleclem/jQuery-MultiSelect#121]
[Awesome plugin!]

I'm trying to programmatically check/uncheck items. I see your example on dynamically creating the entire list (using loadOptions()), but I need to change the checkboxes in an existing list. 

I can use $('#myList').val(['1','3']) (where the values in my list are numbers) and it seems the list knows that items "1" and "3" are selected, but a checkmark doesn't appear.

Thanks! Apologies for bugging you! I'm stumped..

**Comment by Sachelis** [comment]
I ended up doing this using:

`$("#myList option[value='" + value + "']").attr('selected', 'selected');`

(I actually loop through the array of values calling per above.)

I thought (incorrectly) that I could pass the array using the val() function.

**Comment by nobleclem** [comment]
The <select> list and the multiselect list are two different things.  The multiselect list which is what the user sees updates the <select> list selected values.

So you could do `$('#myList').val(['1','3'])` however you would then need to reload `$('#myList').multiselect('reload');` the multiselect list for the changes to propagate to it the list with the checkboxes.
