### ISSUE TITLE
(un)selectAll behaviour

### ISSUE THREAD

**Issue by nlv02636** [nobleclem/jQuery-MultiSelect#122]
It would be nice to have a callback function for the selectAll event, or at least the option to iterate through the onOptionClick function if defined.

I'm currently using onControlClose, but  this happens after I close the box rather than instantly like the onOptionClick event.

Many thanks for your work so far!

Dave

**Comment by nobleclem** [comment]
added onSelectAll callback in 2.4.8

**Comment by nlv02636** [comment]
Fantastic - great service!
