### ISSUE TITLE
Programmatically Check Entry When No Entries Are Selected

### ISSUE THREAD

**Issue by RoyClem** [nobleclem/jQuery-MultiSelect#128]
When a user unselects all options, I need to programmatically select on of the options in the list.

For example, the list contains checkboxes for the following options with the first entry checked.

Option 1
Option 2

The user selections Option 2 (and observes the effect on the app).

At this point, both entries are checked.

But then the user unchecks Option 2 and Option 1.

At that point, I need to programmatically check one of the options in the list so that the list never has an unchecked entry.

How would I accomplish this?

Thanks!

**Comment by nobleclem** [comment]
You should be able to use something like this https://github.com/nobleclem/jQuery-MultiSelect/issues/43 to accomplish what you want.  You could use `$(element).val().length` to check if any options are selected and then select whatever one you want like the example in the other issue shows.
