### ISSUE TITLE
Can I select the option using Javascript from array/json ?

### ISSUE THREAD

**Issue by zeroseed** [nobleclem/jQuery-MultiSelect#130]
Hi , 
There's function for select an option by JS itself ?
So i want to select/check the option but using JS from array or json data in some scenario 
it is possible ? 

Thank you

**Comment by nobleclem** [comment]
There are a couple ways of dealing with it.  Basically you just need to make the options selected like its a normal select list and then reload the multiselect plugin `$('#myList').multiselect('reload');`

See issues: #121 & #82 for examples.
