### ISSUE TITLE
Example of callback

### ISSUE THREAD

**Issue by mifydnu** [nobleclem/jQuery-MultiSelect#136]
OK, it's been 30 years since I spent much time coding. The last time I used a callback was with X Windows, Xlib, and Athena. Forgive me - this javascript, jquery business is making my head hurt. I'm not sure if this is the right place to ask the question (if not, I feel certain someone will let me know, perhaps politely, perhaps not), but here goes: is there an example/demo of using any of the callback functions? I would love to take advantage of the onControlClose callback but alas, I am unable to grok how to define it. Help of any sort would be much appreciated. Thanks. 

Awesome plugin, BTW.

**Comment by SB401** [comment]
Have a look at the demo for this library at https://github.com/nobleclem/jQuery-MultiSelect. The last example may give you some ideas. Otherwise best as the question on stackoverflow(https://stackoverflow.com/)

**Comment by nobleclem** [comment]
I have several demos on my [demo site](https://springstubbe.us/projects/demos/jquery-multiselect/).  Hopefully some of those help guide you to what you might need.

**Comment by mifydnu** [comment]
All good. Thanks again - I think I have things figured out now. Cheers.

-Andy
