### ISSUE TITLE
adding data-tags to options

### ISSUE THREAD

**Issue by GrassGetsGreener** [nobleclem/jQuery-MultiSelect#138]
Hey,

is it currently possible (or will it be made possible) to add data-* attributes to options?

E.g. maybe dynamic populated list array could look like this:

        ```
       var options = [{
            name   : 'Option 1',
            value  : 1,
            checked: false,
            data: {id=1, foo=bar}
        },{
            name   : 'Option 2',
            value  : 2,
            checked: true,
            data: {id=2, bar=foo}
        },{
            name   : 'Option 3',
            value  : 3,
            checked: false,
            data: {id=3, foo=bar}
        },{
            name   : 'Option 4',
            value  : 4,
            checked: true,
            data: {id=4, bar=foo}
        },{
            name   : 'Option 5',
            value  : 5,
            checked: false,
            data: {id=5, foo=bar}
        }];
     ```

so that when it renders it outputs as:

```
<option value="1" data-id="1" data-foo="bar">Option 1</option>
<option value="2" data-id="2" data-bar="foo">Option 2</option>
<option value="3" data-id="3" data-foo="bar">Option 3</option>
<option value="4" data-id="4" data-bar="foo">Option 4</option>
<option value="5" data-id="5" data-foo="bar">Option 5</option>
```
?

**Comment by nobleclem** [comment]
try 

 ```
   var options = [{
        name   : 'Option 1',
        value  : 1,
        checked: false,
        attributes: {
            'data-id': '1',
            'data-foo': 'bar'
        }
    },{
        name   : 'Option 2',
        value  : 2,
        checked: true,
        attributes: {
            'data-id': '2',
            'data-bar': 'foo'
        }
    },{
        name   : 'Option 3',
        value  : 3,
        checked: false,
        attributes: {
            'data-id': '3',
            'data-foo': 'bar'
        }
    },{
        name   : 'Option 4',
        value  : 4,
        checked: true,
        attributes: {
            'data-id': '4',
            'data-bar': 'foo'
        }
    },{
        name   : 'Option 5',
        value  : 5,
        checked: false,
        attributes: {
            'data-id': '5',
            'data-foo': 'bar'
        }
    }];
 ```

**Comment by GrassGetsGreener** [comment]
Hey,

it half-works (well, it works just not as I'd expect) :)

It adds it ok to the options, but the selected <li> element doesn't have the data attributes applied to it. I can write something around it so it searches the options for the li value and get it that way, but I suppose I expected it would add it into the <li> as well

Thanks,

**Comment by nobleclem** [comment]
The data attributes are written to the `<option>` and the `<input type="checkbox">` elements.  I added an example to the [demo](https://springstubbe.us/projects/demos/jquery-multiselect/) page.

**Comment by GrassGetsGreener** [comment]
Hey @nobleclem,

that they are - but they're not to the `<li>` elements when selected from what I inspect (can add screenshots if needed?)

**Comment by GrassGetsGreener** [comment]
Hey @nobleclem,

that they are - but they're not to the `<li>` elements when selected from what I inspect (can add screenshots if needed?)

**Comment by nobleclem** [comment]
I think I am not understanding the need for the data attribute to be placed on the `<li>`, can you elaborate more as to the problem you are trying to solve?

**Comment by GrassGetsGreener** [comment]
Essentially it uses the data-* attributes for an AJAX call. Because it's all dynamically made, it uses li.selected in a $.each loop

**Comment by nobleclem** [comment]
well if you had something like this you can always get the data attributes as such.
```
$('li.selected').each(function(){
    var fooDataAttr = $(this).find('input').attr('data-foo');
});
```

**Comment by GrassGetsGreener** [comment]
That's what I'm currently doing - so it's not really much of an issue anymore, just wanted to confirm I was doing it the "right" way - jQuery/JavaScript is not my forte. :) happy to close ^.^
