### ISSUE TITLE
example in section "Proper positioning of the option popup" doesn't work

### ISSUE THREAD

**Issue by tbl0605** [nobleclem/jQuery-MultiSelect#14]
Hi,
the example in section "Proper positioning of the option popup" of page http://pbauerochse.github.io/searchable-option-list/examples.html doesn't work (using Firefox 45.0).

Thierry.

**Comment by nobleclem** [comment]
That is a different plugin.

**Comment by tbl0605** [comment]
I need some sleep, sorry for the mistake ;)
