### ISSUE TITLE
How to bind jsonarray data into jquery multiselect control in jquery

### ISSUE THREAD

**Issue by Kannanprs84** [nobleclem/jQuery-MultiSelect#140]
I have a json list and list having ID and name . I should bind name and ID into jquery multiselect control using jquery.

I could not able to dynamically bind the json array data.  Please do needful for me ASAP

**Comment by nobleclem** [comment]
See the demo "DYNAMICALLY POPULATE LIST" on the [demos](https://springstubbe.us/projects/jquery-multiselect/) page.
