### ISSUE TITLE
Using more than one multiselect on a page

### ISSUE THREAD

**Issue by rhdyes** [nobleclem/jQuery-MultiSelect#141]
I am using this plugin but when I add more than one select element on one page only the first element populates the text bar.  I am able to choose multiple items in the second and third elements but the selections do not show up in the text bar.

here are the elements in my elements and the code to populate them and then initialize 
This the first one and it works fine.

$('<select>').prop({name:"Mrnum[]",id:"Mrnum",multiple:"multiple"})   

             $("#mrnum").multiselect({
                columns: 4,
                placeholder: 'Select Residents'
            });
These subsequent ones do not populate the text bar. Here is one of them and the code
$('<select>').prop({name:"nonemployeemchnum[]",id:"nonemployeemchnum",multiple:"multiple"}) 

$("#nonemployeemchnum").multiselect({
                columns: 4,
                placeholder: 'Select Others'
            });

**Comment by nobleclem** [comment]
I am not sure what problem you are having.  What text bar?  Also that code doesn't define the element as a select element so that would not allow the plugin to load.
