### ISSUE TITLE
Changing the location of the option box

### ISSUE THREAD

**Issue by SB401** [nobleclem/jQuery-MultiSelect#142]
Hi Patrick,

Is there a build-in method to make the options appear above the button rather than below. I am trying to use multiselect close the the bottom of the page and it would be nice if the option list appeared above the button.

Cheers

SB

**Comment by nobleclem** [comment]
There is currently nothing built in however you might be able to replicate the desired behavior by adding some custom css to your page like:
```
.ms-options-wrap > .ms-options {
    top: 10px
}
```
I tested that only on my demo page.

**Comment by SB401** [comment]
Thanks mate
