### ISSUE TITLE
Custom Colors for Options and Option Group

### ISSUE THREAD

**Issue by aalasolutions** [nobleclem/jQuery-MultiSelect#144]
Hi, 

I have used your plugin for a project, I have to show different colours for different options and option groups. I have modified the code, and kept my CSS in my own files, just passed classes via `data-color=""` in `option` tag

![image](https://user-images.githubusercontent.com/1493178/47291265-6a8f3a80-d61c-11e8-833d-1a4f7181ddc7.png)

If this is something which can be added in plugin, do let me now and I'll create a PR

**Comment by nobleclem** [comment]
In my 18 years of development I have never ran into a use case for something like this.  The plugin is designed to be a bare bones multiselect that is easily customizable for individual use cases.  There are plenty of overbuilt multiselect plugins available.

Glad to see you were able to mold the plugin for your use case.  I hope you were able to use the "optionAttributes" config to perform this.  I think with that and the way you state you are targeting via CSS that should have required no modification of the plugin.
