### ISSUE TITLE
Label Changes for Option Group selection

### ISSUE THREAD

**Issue by aalasolutions** [nobleclem/jQuery-MultiSelect#145]
I am trying to look for an option which is available in http://wenzhixin.net.cn/p/multiple-select/docs/#with-optgroups

If you select Group 1, in Label you will see it is showing `[Group 1]` and if I select only one option within group it will show `[Group 1: 1,4,5]` giving a clear indication of which item from which group is selected. 

This can be added as an option, which user can toggle.

**Comment by nobleclem** [comment]
I can see how this feature can be appealing to some, however I am not sure its a common must need feature.  However looking through how something like this could be implemented through a callback, I think what I could add is a callback at the end of the `_updatePlaceholderText()` function that could allow a user to override the placeholder text being set.
