### ISSUE TITLE
duplicate multiselect dopdown

### ISSUE THREAD

**Issue by anu482** [nobleclem/jQuery-MultiSelect#156]
Hi,

In my project we are using multi select dropdown with check box and we are having different childform on parent form whenever going and come from child form to parent form  duplicate the multi select dropdowns are coming

**Comment by nobleclem** [comment]
I don't understand what your issue is.

**Comment by anu482** [comment]
we are using bootstrap multiselect plugin 
 
 
 
 

I don't understand what your issue is.

**Comment by anu482** [comment]
![multi selct dropdown](https://user-images.githubusercontent.com/52497727/60641192-6fadb600-9e48-11e9-9fba-e15cbb56bdb1.PNG)


please find attachment for your understanding

**Comment by nobleclem** [comment]
So the multiselect only needs to be initialized once.  I suspect you are initializing it when showing that form and it's duplicating the input.  However with little information and no actual code it's hard for me to help determine what is going on.
