### ISSUE TITLE
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by webservsol** [nobleclem/jQuery-MultiSelect#159]
Integrate your plugin with a certain CMS that requires jquery-1.7.1.min.js can't use higher version of jQUERY is causing issues on line 628

`optionsList.append( containers );`

Once this line is commented the error is gone however the values aren't loaded while if uncommented it returns an error

> Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

Any suggestions and help is highly appreciated.

**Comment by nobleclem** [comment]
I suspect that it has to do with this [jquery issue](https://bugs.jquery.com/ticket/11231).  So based on that it changing line 628 to maybe 
```
containers.forEach(function( item, index ){
    optionsList.append( item );
});
```

or

```
for( var i=0; i < containers.length; i++ ) {
    optionsList.append( containers[i] );
}
```

Out of curiosity what CMS are you using?

**Comment by wmitc2375** [comment]
That fixed the issue, thanks again!
