### ISSUE TITLE
Checkbox formatting issues

### ISSUE THREAD

**Issue by SoftCircuits** [nobleclem/jQuery-MultiSelect#16]
Does anyone know why I'm getting display issues? For me, the checkboxes don't seem to line up with the text. And the text even seems to overwrite part of the checkbox.

I created an HTML page from scratch. The only styling I added was setting the font-size and font-family, and using the CSS file that comes with jQuery-MultiSelect.

![multiselect](https://cloud.githubusercontent.com/assets/3191331/14330893/e82a6dc4-fbff-11e5-84a6-14bde26f3833.jpg)

**Comment by nobleclem** [comment]
Double checked my work and I don't reset default styles applied to the list.  Probably something I should add.  So most likely what you are seeing is some extra margin/height/padding that is most likely a default browser style.  Along with the bullets.

**Comment by SoftCircuits** [comment]
I've been playing with this some more. To be honest, I'm very curious how you could have very different results with the same CSS. Are you resetting the default styles someplace else?

With respect to the item checkboxes not lining up with the checkbox label text, if I comment out the `position: absolute;` in the following block, it seems a lot better. Although the margins and kind of excessive.

`.ms-options-wrap > .ms-options > ul input[type="checkbox"] {
    margin-right: 5px;
    position: absolute;
    left: 4px;
    top: 7px;
}`

**Comment by nobleclem** [comment]
Like I said... the plugin is not applying reset styles.  I by default always reset my css before working which is why the demo creates a different result than what you are getting.  The styling of the plugin is intended to be minimal and easy to override to someones needs.

Hope that clarifies things.
