### ISSUE TITLE
Was working but now not with jquery-1.7.2.min.js

### ISSUE THREAD

**Issue by wmitc2375** [nobleclem/jQuery-MultiSelect#160]
I am new to Javascript and jQuery.  I love your control, thanks for offering it for use.  It was working fine but a friend told me the reference  to https://code.jquery.com/jquery-1.10.2.js was conflicting with another required version of jQuery my page needs for a different control.  So I just removed the reference to the 1.10.2 version and also tried even leaving the line in but swapping to the 1.7.2.min.js version (already referenced at top of page) but that caused the control to render on the form but it has no choices and the standard dropdown continue to show with the choices.  So something apparently needs version 1.10.2 or very possibly I need to do something different on my page.  Any ideas how to fix and should your control work with 1.7.2?  Thanks!

**Comment by nobleclem** [comment]
If you can't use a newer version of jQuery then you are probably running into the same issues as #159 I have a possible code adjustment that you could make listed in that issue.

**Comment by wmitc2375** [comment]
Thanks for the quick reply!  I will read over and see about making that adjustment.

**Comment by wmitc2375** [comment]
That change fixed the issue, thanks!
