### ISSUE TITLE
Wrap .ms-options-wrap button span items in single spans

### ISSUE THREAD

**Issue by ca-dsgn** [nobleclem/jQuery-MultiSelect#163]
Hi @nobleclem ,

thank you for your great work on jQuery-Multiselect. I was looking for a great multiselect solution (based on jQuery) and found your plugin.

My questions is: is it possible to easily wrap the selected items inside of .ms-options-wrap button span?

Currently a selection looks like this:

```
<button type="button">
  <span>Item 1, Item 2</span>
</button>
```

I would love to have something like this:

```
<button type="button">
  <span>
    <span>Item 1</span>
    <span>Item 2</span>
  </span>
</button>
```

Thank you very much in advance.

Best
Christian

**Comment by nobleclem** [comment]
Added a new callback `onPlaceholder`.

```
$('select[multiple]').multiselect({
    onPlaceholder: function( element, placeholder, options ) {
        placeholder.html( '<span>' + options.join( ',</span> <span>' ) + '</span>' );
    }
});
```

**Comment by ca-dsgn** [comment]
That's great. Thank you for the quick update!

Could you also add the git version tag 2.4.17 so that my package manager can find your update?

Thank you very much.
