### ISSUE TITLE
css optgroup label problem

### ISSUE THREAD

**Issue by zokanzi** [nobleclem/jQuery-MultiSelect#165]
My optgroup labels white color on bootstrap. Label appear only select text. This fixes when I remove bootstrap css. How I change my optgroup label style. I tried a lot of things but these methods didn't solve my problem. 

Thanks for your helps... 

![Capture](https://user-images.githubusercontent.com/972750/68518209-fca3c880-029b-11ea-9466-ee4299586fe4.JPG)

**Comment by nobleclem** [comment]
Should be able to target it like any other element on the page.  Just use your browsers inspector to figure out the best way to target it in your CSS.  That should allow you to override bootstraps default styling for that particular element.
