### ISSUE TITLE
Allow HTML in <option> [Improvement]

### ISSUE THREAD

**Issue by surindersinghva** [nobleclem/jQuery-MultiSelect#169]
I cannot thank you enough for this very sleek plugin. Excellent work. 

Is there a way to allow HTML in the options' items? I am using a glyphicon (question-mark) and a tooltip to show 'more info' about the item listed. It was possible in Bootstrap Multiselect, however, I gave up on Bootstrap to reduce the toll on my application and developed a minimalistic theme instead. 

Please suggest.

**Comment by nobleclem** [comment]
So just to note that this now can be done in version 2.4.18 but you will have to use the `loadOptions` method as html is not allowed in `<option>` elements.
