### ISSUE TITLE
Required does not working

### ISSUE THREAD

**Issue by ramkumar-eccma** [nobleclem/jQuery-MultiSelect#170]
Hi,

Firstly, its really a nice plugin but the HTML5 required is not working I tried to add required attribute onLoad but it doesn't works at all.

Am using jquery validation **jQuery Validation Plugin - v1.19.1**  if it works am very happy.

I hope a positive response from your end
![1](https://user-images.githubusercontent.com/15085766/77951032-0b405a00-72e7-11ea-9e12-11a296b7c57a.png)

**Comment by nobleclem** [comment]
I am not sure there is anything that can be done on the plugin side of things.  What happens is that the native <select> element is hidden and a new set of elements is added to provide the interface.  What you would need to do is write some javascript that mimics the native HTML5 required attribute when someone attempts to submit the form.
