### ISSUE TITLE
More than 1 multi select dropdownlist issue

### ISSUE THREAD

**Issue by anirudha24d** [nobleclem/jQuery-MultiSelect#177]
Hi ,

I am using Multi select dropdown plugin and finding it very useful.

I would like to guidance about following scenarios

1. I have 2 multi select dropdpwnlist in my code and  at  the time of loading dropdown for the first time, i want to display  count for previously selected items from the dropdpwnlist in the place holder for both dropdwnlists . ( we are getting   count for previously selected items for both lists  from database). But currently  always  2nd dropdownlist selected item count is displayed on place holder for both dropdownlist. For exampl for 1st dropdpwnlist  if 2 items are previously selected and  for 2 nd dropdown if 3 items are previously selected and on place hoder of both dropdwnlist it shows "3 Items selected" instead of this, i should shows as "2 items selected " for 1st dropdownlist and "3 items selected" for 2nd dropdownlist.

2. On  the  dropdown list load,  we show number of previously selected items ( we are getting this count  from database). but whenever any item is selected, that  cout is replaced with current selected item count.

**Comment by nobleclem** [comment]
If a user has already selected items saved in the database you need to load those selections back into the select list as selected.  Then when they (un)select new items the correct "# selected" will be shown.

You have to think of this as a normal select list.  All this plugin does is makes the interface a little easier for the user to select options.
