### ISSUE TITLE
Item Sort Order

### ISSUE THREAD

**Issue by SoftCircuits** [nobleclem/jQuery-MultiSelect#18]
I have added items to my <select> element in the correct order. But that is not the order they the plugin displays them.

Is there a way to prevent the plugin from changing the order?

**Comment by nobleclem** [comment]
Do you have a demo?  Are you using multiple columns?

The plugin should be creating the list in the same order that they options are in the standard select list.

**Comment by SoftCircuits** [comment]
I've returned to this issue. I will report back but what I'm seeing is that `<option>` items are being added in ascending order according to the value, instead of the original order. That doesn't work for us and I'm not sure why it'd do it that way. If I figure out what's happening.

**Comment by SoftCircuits** [comment]
So, JavaScript is not my main language but the problem seems to be here.

    $(this).children('option').each(function(){
        groupOptions[ $(this).val() ] = {
            name   : $(this).text(),
            value  : $(this).val(),
            checked: $(this).prop( 'selected' )
        };
    });

The value is used to indicate the array position, thus sorting all elements by the value. Would be better to simply append instead in order to maintain the same order.

I can rework this, but wonder if:

1. Is there a reason it's done this way that I should be aware of?

2. If this is something that you would want to rework yourself, I would prefer to use your version. Among other reasons, it would allow me to use future versions of this plugin without modification.

Thanks.
