### ISSUE TITLE
jQuery-MultiSelect Performance Issue

### ISSUE THREAD

**Issue by balakrishnakoduru05** [nobleclem/jQuery-MultiSelect#182]
I am using jQuery-MultiSelect in my Project.
We have one dropdown with values 21000 it is taking time to convert to jQuery-MultiSelect box.
Even opening the options also it is taking 3 to 4 secs.

Can some one Please help me to fix this issue.

Below code i am using to convert to jQuery-MultiSelect

if($('#'+controlId)){
		$('#'+controlId).multiselect('reload');
		$('#'+controlId).multiselect({
			columns: 1,
			placeholder: '',
			search: true,
			searchOptions: {
				'default': 'Search'
			},
			selectAll: true
		});
	}

**Comment by nobleclem** [comment]
Unfortunately there is a limit to what this plugin can handle.  Once you start getting an obscene number of items like you are trying to place in it there is a limit to how fast it can handle it.

I present two solutions to the problem in issue #146 (last comment).
