### ISSUE TITLE
Options box not aligned with component

### ISSUE THREAD

**Issue by aguevaracaprio** [nobleclem/jQuery-MultiSelect#184]
When using the multiselect under a regular div, the options component is not aligned with the dropdown
I've seen the demo code and it is not happening there, so not sure if my html is wrong or I'm missing something
```
<div id="wrapper" style='display: flex; align-items:stretch'>
</div>
```
That's the wrapper div 

![Screenshot from 2021-11-30 17-03-47](https://user-images.githubusercontent.com/78170103/144136756-9e6c799a-3433-41da-863b-b7c098cb8be1.png)
The options that are showed correspond to the Group 2 dropdown

**Comment by aguevaracaprio** [comment]
I was able to solve the issue by removing `position: absolute' in the rule .`ms-options-wrap > .ms-options `

**Comment by sam888k12** [comment]
Hi,

I am having the same issue but the fixes above did not work.  I removed first left: 0 then position: absolute

This is what I have now.
.ms-options-wrap > .ms-options {
    width: 100%;
    margin-top: 1px;
    margin-bottom: 20px;
    background: white;
    z-index: 2000;
    border: 1px solid #aaa;
    overflow: auto;
    visibility: hidden;
}
![MultiSelectScreenshot](https://user-images.githubusercontent.com/95718251/145101654-52087b60-d37e-4c93-b300-407a13cdfdd1.jpg)

**Comment by aguevaracaprio** [comment]
Hey Sam. I'll recommend wrapping your select in a div component 
<div>
<select ...>
</div>
And remove the left: 0. That was the html structure that I followed for it to work

**Comment by sam888k12** [comment]
Thanks but I tried that and still getting the same issue.  I think I am having trouble getting the stylesheet to talk to my select statement.  This the div code I wrapped around it: <div class="ms-options-wrap">.  Should I be using something else?

**Comment by aguevaracaprio** [comment]
I can't see your code, but select tags can't be customized that much. That's why the author created a button tag instead to add all this functionality. I would recommend opening the "Inspect" mode of your browser and inspect the option box and play around with the css properties that are there. Start by adding back all the original code and then start playing around by removing and adding new attributes

**Comment by nobleclem** [comment]
The updated jquery.multiselect.css file should resolve this.  Not sure why I didn't have that particular bit of css in there all along.

**Comment by sam888k12** [comment]
Thank you this issue has been resolved on my end with the updated css.
