### ISSUE TITLE
Checkbox default to checked, Dark blue hover color

### ISSUE THREAD

**Issue by sam888k12** [nobleclem/jQuery-MultiSelect#185]
[Hi,]([blueBox.docx](https://github.com/nobleclem/jQuery-MultiSelect/files/7705121/blueBox.docx))

I am using the multiselect on a webpage and everything is working well except I can't figure out 2 things.
1. the first checkbox in my list is defaulting to checked. I want all checkboxes to be unchecked upon loading
2. when I hover over the dropdown list with the multiselect, it is changing to a dark blue (see screenshot).  I want to change the hover color.  

I have not adjusted the .css or .js files from the download.  Here is my select statement and script.

<select class="ms-options-wrap" name="[U_TD_DELIVERY]Target_StudentsServedText" multiple="multiple" id="Target_StudentsServedText" onChange="saveValuesMulti(this,document.getElementById('Target_StudentsServed'))" required>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> 
<script src="jquery.multiselectSD.js"></script>
<script>
$('select[multiple]').multiselect({
    columns: 1,
    placeholder: 'Select Students',
    maxPlaceholderWidth: 500,
    maxHeight : 300, 
    maxWidth: 500
});
</script>

And looking at the script, it is also not using the 'Select Students' in the placeholder instead it is defaulting to the first value in the list.  I used this script on a different dropdown on the same page without these issues.

thanks,
Samantha
[blueBox.docx](https://github.com/nobleclem/jQuery-MultiSelect/files/7705126/blueBox.docx)

**Comment by nobleclem** [comment]
1. That means something is selected already in your list.  I am utilizing the preferred detection method of `$(this).prop('selected')` on lines 419 & 429 of jquery.multiselect.js.
2. I suspect your sites styles are coming into play.  You will have to override them with additional CSS.

There is an included demo.html file that you can utilize to test with.

With both cases either something isn't what you think it is or something else on the site is doing something that you are not aware of.  Unfortunately that debugging is something you will have to work through as I don't see how its the plugin causing it.
