### ISSUE TITLE
Parent Clipping

### ISSUE THREAD

**Issue by AMacro** [nobleclem/jQuery-MultiSelect#188]
Drop-down is getting clipped by parent container - expected it should float over just about everything
![image](https://user-images.githubusercontent.com/22724915/158051624-8f0706cd-a0f6-4f99-ad42-16c78fd1217d.png)
 
I've made an example of this behaviour here: [https://jsfiddle.net/Macka/eyuda913/2/](https://jsfiddle.net/Macka/eyuda913/2/)

I expected the drop-down to either float over just about everything, or to auto scroll.
I was able to sort of get this by limiting the height, and maybe it is a case of doing a calculation on the table/parent container outside of the plugin and updating the list if the parent changes.

Using the height limit, I've achieved this, but I feel it should be automatic:
[https://jsfiddle.net/Macka/eyuda913/4/](https://jsfiddle.net/Macka/eyuda913/4/)
![image](https://user-images.githubusercontent.com/22724915/158051972-a8b3c1a5-026a-426b-a446-03e4ca862f3b.png)

**Desktop:**
 - OS: Win 10 x64
 - Browser: Chrome 99.0.4844.51
 - Browser: Firefox 98

**Comment by nobleclem** [comment]
So there are limited options to handling this issue.  I never intended this plugin to be a one size fits all yet more of a starter dropdown that could be user enhanced.  I have run into similar issues and either just make sure the blocking element has a min height large enough to accommodate the list or do something like these options below.  Usually for me the first case resolves my problems.

You can override the CSS to accommodate your use case.
```
.ms-options-wrap {
    position: inherit;
}
.ms-options-wrap > .ms-options {
    left: inherit;
    width: auto;
}
```

The only other thing I could think of adding is another callback something like onControlOpen which would allow you to write some custom javascript to determine the max-height automatically.
