### ISSUE TITLE
There is no way to get all selected items values not the text.

### ISSUE THREAD

**Issue by webhay** [nobleclem/jQuery-MultiSelect#19]
Hi,
  Thanks for your free jquery plugin, I don't see any built in way to get all the selected items values not the text. Please let me know if it is already there and I missed or please fix it and let me know. Thank you so much for your help

**Comment by nobleclem** [comment]
You should be able to just check your original select list for the selected items.  When you click a checkbox it automatically sets/unsets the selected property of the option in the original select list.
