### ISSUE TITLE
Useful callback function: onSelect, onUnselect

### ISSUE THREAD

**Issue by StudentLin** [nobleclem/jQuery-MultiSelect#190]
Hey Guys,

Appreciate for your great contribution of such useful plugins, it's helped me to save lots of effort.

But while i'm using it i dont't find any callback methods when i SELECT a option or UNSELECT a option,  
so now i'm using onOptionClick( element, option ) as a workaround, but i have to tell out which operation(SELECT/UNSELECT) it is. It's not so convnient.

So is there any posibileties to provide this kind of new features? That will be absolutely help us.
Please correct me if i have any misundersdanding, thank you again.

**Comment by nobleclem** [comment]
Glad you are getting good use out of it.

`onOptionClick` would be the correct callback to use.  It is easy to add a check for if the option was selected or not.  There is a demo of this on the [demo page](https://springstubbe.us/projects/jquery-multiselect/) titled "**Event when option (de)selected**".

```
$('select[multiple]').multiselect({
    onOptionClick: function( element, option ){
        if( $(option).prop('checked') ) {
            // SELECTED OPTION CODE HERE
        }
        else {
            // UNSELECTED OPTION CODE HERE
        }
    }
});
```

**Comment by StudentLin** [comment]
Hi support,

It works, thank you for your quickly response :)
