### ISSUE TITLE
add ability to write new value if it not found in list

### ISSUE THREAD

**Issue by pbelskiy** [nobleclem/jQuery-MultiSelect#192]
First of all thanks for this great plugin!

**Is your feature request related to a problem? Please describe.**
In some cases of usage your plugin I wanna write some custom value if it not found in original list,
and submit it to server.

**Describe the solution you'd like**
When no item is found I suggest to add it to list by pressing enter button.

**Describe alternatives you've considered**
I've create some hack in your plugin, but it's incorrect, so could you add this future, please.

**Additional context**
No

**Comment by nobleclem** [comment]
Yeah that is going to be a custom thing to do.  You should be able to implement what you need using the various [Callbacks](https://github.com/nobleclem/jQuery-MultiSelect#callbacks). You might need to implement your own event listener which could be initialized within the `onLoad` callback.
