### ISSUE TITLE
Option/Improvement to have list without select/default option.

### ISSUE THREAD

**Issue by narsireddypanta** [nobleclem/jQuery-MultiSelect#193]
Currently this dropdown provides default option i.e select which means user may to may not select this dropdown but it would be better to provide an option to have default option or not, If this functionality is already there kindly provide more details.

**Comment by nobleclem** [comment]
I am not sure what you are asking for.  If it is just having the select list defaulted to a particular value then you can set that in the native `<select>` list and the plugin will have that option selected on load.
