### ISSUE TITLE
Show some items disabled in jQuery-MultiSelect with css

### ISSUE THREAD

**Issue by michelerossige** [nobleclem/jQuery-MultiSelect#197]
Well done with https://github.com/nobleclem/jQuery-MultiSelect/issues/51
It works fine.
But if I want to give a css property (like different background color) to disabled items, what can I do?
I've tried any way but no result.
May you please help me?
What css string do I have to insert?
Tried with
.ms-options-wrap > .ms-options > ul li.disabled label {
but It doesn't work.
Thanks very much in advance :)

**Comment by nobleclem** [comment]
Not tested but you might be able to do something like:

```
$('select[multiple]').multiselect({
    onLoad: function( element ){
        $(element).next('.ms-options-wrap').find('.ms-options input[disabled]').each(function(){
            $(this).closest('li').addClass('disabled');
        });
    }
});
```

Then you can just target `.ms-options-wrap > .ms-options li.disabled` with css.

**Comment by michelerossige** [comment]
Thank you very much, Patrick.
Wonderful job.
Tell me please where can I leave a money tip for your sincere help.
