### ISSUE TITLE
Make options DIV respect screen size

### ISSUE THREAD

**Issue by carlosSFC** [nobleclem/jQuery-MultiSelect#199]
Have the options DIV dynamically adjust its position relative to the screen size and/or container width. In some scenarios options display off screen and aren't visible to the user (see screenshot).

![image](https://user-images.githubusercontent.com/101423464/226469155-78d95e8b-ad28-47a4-a115-d2bdeac759b5.png)

**Comment by nobleclem** [comment]
The `.ms-options` div has a default width of `100%`.  So I suspect that there is something else going on with your specific implementation.
