### ISSUE TITLE
Replace comma with newline in the placeholder

### ISSUE THREAD

**Issue by leonta2010** [nobleclem/jQuery-MultiSelect#20]
I need help...Is it possible to replace newline instead comma in the placeholder? How do you go about?  Once again, thank you for sharing you code.  Leon

**Comment by nobleclem** [comment]
You could probably utilize the onOptionClick callback to do a search replace for the comma and replace with a newline character.

This is untested but might work.
'''
onOptionClick: function( element ) {
    $(element).next('.ms-options-wrap').find('> button:first-child').replace( /, /g, "\n" );
}
'''
