### ISSUE TITLE
onControlClose -- take action only if options changed

### ISSUE THREAD

**Issue by carlosSFC** [nobleclem/jQuery-MultiSelect#202]
I have a select element configured to use the onControlClose callback and it's working as intended. However, what I'd like to happen is for the code in the onControlClose callback to only run if/when the selected options change. As it stands now, every time the options list is closed the code runs.

**Comment by nobleclem** [comment]
Not tested but you could do something like:

```
$('select[multiple]').multiselect({
    onControlClose: function( element ){
        // no change, skip
        if( $(element).data('lastVal') != $(element).val().join(',') ) {
            return;
        }

        $(element).data('lastVal', $(element).val().join(',') );

        // RUN OTHER CODE HERE
    }
});
```
