### ISSUE TITLE
Erasing all optios 

### ISSUE THREAD

**Issue by ebrahimtaher** [nobleclem/jQuery-MultiSelect#208]
Dear sir..
Thanks or your valuable code for the multiselect .
I want to remove all options in the list and replace with new options usin jquery call. I am able to add options but i face 2 problems 
1- old options have not been removed so the list is keep adding the new opt to the current options list.

2- the new options are not reflcted to the list from the first call.  It start to appear after the 2nd call to jquery.
Please help

**Comment by nobleclem** [comment]
1) I have no clue how you are attempting to do this right now.  So its hard for me to assist with your specific issue.
2) There is an [example](https://springstubbe.us/projects/jquery-multiselect/) "Dynamically Populate List" that shows how to populate the list.  By default the 'loadOptions' method will overwrite the existing values.
3) if you are not using the option described above and are manipulating the `<select>` element directly you can always call `$('select[multiple]').multiselect('reload')`
