### ISSUE TITLE
Columns option is not working IE

### ISSUE THREAD

**Issue by eswartaku** [nobleclem/jQuery-MultiSelect#23]
i have used this jquery plugin in my application and tried to use the multiple columns option in my drop down but my drop down is not able to show the values in multiple columns.

Another issue is with the "select all" option if i tried to click on that option it is highlighting all the option values but it is unable to show those values in the text box after deselecting that then it is showing the number.

One thing i am not able to figure it out how to add the select all options in each optgroup. 
Help me with the code if you have any

**Comment by nobleclem** [comment]
What version of IE? Do you have a demo? Debugging without being able to reproduce the problem is very difficult to nearly impossible.

**Comment by eswartaku** [comment]
i am using IE11.
i have figure it out the multiple columns issue.
but not able to solve the select all option issue.
for Select all option issue when i am selecting that option , all the check box are highlighting but the selected number is not showing in the header and when i am again clicking on the select all option this time all the checkbox are deselected and that number previously selected have been shown in the header.

i am facing another issue with the width.
could you plz let me know how to fix the width because when i am giving 160 px initially it is coming correctly but when i select more than 3 values in the select option then that drop down is expanding and not able to figure it out how to restrict that expansion

**Comment by eswartaku** [comment]
Select all option is not working in IE11

**Comment by eswartaku** [comment]
"Select All" issue has been resolved for me. The problem is with jquery version i have used older version 1.7 in that there is a problem with checked option for checkbox. see the below answer.

http://stackoverflow.com/questions/7668826/jquery-triggerclick-not-firing-click-event-on-checkbox 

Resolution: i have used the latest jquery version 2.2.
Hope it will helpful for some other.
