### ISSUE TITLE
Text box not populated 

### ISSUE THREAD

**Issue by mdie1277** [nobleclem/jQuery-MultiSelect#36]
If I give it a data source with elements that are checked, I would expect that the title of these elements would be populated in the input. Am I doing something wrong or is this functionality missing?

**Comment by nobleclem** [comment]
Are you loading the data via javascript or the default targeting of a select list?

**Comment by mdie1277** [comment]
I'm loading it via javascript, and I'm also adding the options to the initial select

**Comment by mdie1277** [comment]
$multiselect.multiselect({
            'search': true,
            'texts': { placeholder: 'Select items' },
            'onOptionClick': onOptionClick
});
$multiselect.multiselect('reload');

var multiselectSource = [];

for (var i = 0; i < autocompleteSource.length; i++) {
                    var currentAutocompleteItem = autocompleteSource[i];

                    $ddlCustomCf.append($(String.format('<option value="{0}">{1}</option>', currentAutocompleteItem.value, currentAutocompleteItem.text)));

                    multiselectSource.push({
                        name: currentAutocompleteItem.text,
                        value: currentAutocompleteItem.value,
                        checked: true
                    });
                }

$multiselect.multiselect('loadOptions', multiselectSource);

this is how I'm doing it

**Comment by nobleclem** [comment]
version 2.2.0 should resolve this issue.  I reworked a bit of code to update the native select list when dynamically loading options.  Beware by default it will overwrite all options in the list.
