### ISSUE TITLE
demo to getting selected items in array

### ISSUE THREAD

**Issue by SahibYar** [nobleclem/jQuery-MultiSelect#37]
Hi @nobleclem very good work
I am very new to jquery, can you please guide me how to fetch all the elements selected by their values or by their names. I am using this with asp:DropDownList and feeding data via asp:SqlDataSource adaptor.

**Comment by nobleclem** [comment]
You don't need to do anything special to access the selected items.  Should be able to get the values from your native select list.

`$('select').val();`
