### ISSUE TITLE
html5 required 

### ISSUE THREAD

**Issue by eleumik** [nobleclem/jQuery-MultiSelect#4]
Hi, 
nice plugin, thanks.

when using html5 [required] attribute, the browser provided message comes out at top of window, on Mozilla. Opera and Chrome show no mesage still not allowing to submit the form. I believe this happens since the original select is hidden, I replaced 

                 // hide native select list
                 $(this).hide();

 with 

                $(this).css({'position':'absolute', 'visibility':'hidden', 'overflow' : 'hidden', 'height' : '2em'});

but unfortunately this works only in mozilla, I think because of visibility:hidden, so I came out with this, that also tries to place the message on bottom of input, like in the image. Probably the margin-top should be calculated somehow.

              $(this).css({'position':'absolute', 'margin-top':'22px', 'margin-left':'6px', 'border':'0px', 'overflow' : 'hidden', 'height' : '1px'});

![testmultiselect](https://cloud.githubusercontent.com/assets/4514393/12059757/ce843e44-af61-11e5-8785-f4441908d6db.png)

Let me know what you think, 
Bye

**Comment by nobleclem** [comment]
I will have to take a look at this particular issue.

Side Note: I hope you are not relying HTML form validation.  That is easy to bypass and you really should be doing validation on the server side at a minimum.

**Comment by eleumik** [comment]
Hi, I am totally on your side for form validation, one of the reason I am interested in this plugin is that is a perfect substitute for select[multiple] on the server side as well (same parameters). I think also HTML5 required is very handy to avoid useless trips to the server. In my case [required] is already present on the select that must be enhanced with your plugin.

**Comment by nobleclem** [comment]
Performed a total overhaul on the plugin and made it so that its more customizable.  You should be able to modify the native element css doing something like this:
```
$('select[multiple]').multiselect({
    onLoad: function( element ) {
        var placeholder = $(element).next('.ms-options-wrap').find('> button:first-child');
        $(element).css({
            display: '',
            position: 'absolute',
            opacity: 0,
            height: 0,
            marginTop: placeholder.outerHeight( true )
        });
    }
});
```

*I decided to do it this way so that it was more flexible with different situations.  So its possible that your suggested fix might cause a problem for someone else.*
