### ISSUE TITLE
onOptionClick Method fires when the option is checked and when unchecked

### ISSUE THREAD

**Issue by Chibuzo** [nobleclem/jQuery-MultiSelect#44]
onOptionClick Method fires both when the option is checked and when unchecked. This is different from what the documentation says.
Meanwhile, the checked property always remain false (unchecked) irrespective of the checked state.
Has anyone confirmed it or is it just me?

Thanks

**Comment by nobleclem** [comment]
I fixed the documentation.  It shouldn't have said "and selected".  Usage for determining if the option was selected is:
```
$('select[multiple]').multiselect({
    onOptionClick: function( element, option ) {
        if( $(option).is(':checked') ) {
                console.log( 'option selected' );
        }
        else {
                console.log( 'option unselected' );
        }
    }
});
```
