### ISSUE TITLE
"texts" options with no effect

### ISSUE THREAD

**Issue by GakuseiDev** [nobleclem/jQuery-MultiSelect#45]
Hi, 

I'm seeing that texts options such as "placeholder" and "selectAll" have no effect, i'm still reading the default values "Select options" and "select all". 

I tried to find out what the issue is by changing some other options but this seems to happen only why the texts.

Here's my plugin call : 
```
$("#multi-select-1").multiselect({
                    columns: 1,
                    texts: {
                        placeholder: 'test1',
                        selectAll: 'test2'
                    },
                    minHeight : 150,
                    search: true,
                    selectAll: true
                });
```
Also, I should like to point out that the "default" option for the search input placeholder text is a reserved word in Jquery plugin and this isn't working either, in my case I mean. 

EDIT: Forget about the "reserved word" mention, I didn't notice the quotes surrounding "default", but it still doesn't effect by the way.

**Comment by KiterSnow** [comment]
search placeholder texts setting should use "search", not "default".
readme is wrong.

**Comment by GakuseiDev** [comment]
Thanks
