### ISSUE TITLE
Need to clear selection

### ISSUE THREAD

**Issue by sarath2** [nobleclem/jQuery-MultiSelect#46]
How can I clear selected from external event(eg: button click)?

**Comment by nobleclem** [comment]
A couple options depending on your preference.

```
$('select[multiple]').next('.ms-options-wrap').find('input:checked').trigger('click');
```

```
$('select[multiple]').multiselect('reload');
```

**Comment by sarath2** [comment]
Thanks @nobleclem option 1 working well for me, 2nd not functioning.

**Comment by nobleclem** [comment]
Yup now that I am looking at that again and thinking about it it wouldn't work.  Glad the first option works.
