### ISSUE TITLE
Limiting the data loaded onto the selector

### ISSUE THREAD

**Issue by sparkhee93** [nobleclem/jQuery-MultiSelect#5]
Hi, first of all, this is a great plugin -- it's exactly what I've been looking for for my application.

I was just wondering if there's any way to limit the number of data being loaded. If I have a store with a million or two items and I was retrieving from that, I want to be able to limit the load so that it won't be too laggy. In turn, through searching for the item, it would bring up the non-loaded item in which I can now check.

Is there anything I can do to achieve that effect?

**Comment by nobleclem** [comment]
With the code in the current state I don't think there is a way to do what I think you are wanting.  It has really been created as a simple plugin.

However with that said I have been considering refactoring the code a little and making it easier to interface with.  I have (not published yet) finished a first draft of the code refactoring and am now able to focus on creating callbacks, public methods, and enhancements to add the ability to do more.

I am not sure I want to put a ton of functionality into the plugin but more so make it easier to allow people to do that themselves.

Hopefully I can have an update ready for release this week that will make it easier for you to add the remote api call to retrieve and update select the select list.

**Comment by sparkhee93** [comment]
Sounds good. Will be looking forward to it.

**Comment by nobleclem** [comment]
New overhauled code is now available.  You should be able to use the following items to accomplish what you want.  You will have to write some custom logic to accomplish what you want.

```
$('select[multiple]').multiselect({
    searchOptions: {
        onSearch: function( element ) {
            var newOptions = [
                {
                    name: 'Option Name 1',
                    value: 'option-value-1',
                    checked: false
                },
                {
                    name: 'Option Name 1',
                    value: 'option-value-1',
                    checked: false
                },
            ];
            $(element).multiselect( 'loadOptions', newOptions );
        }
    }
});
```

You will need to also manually set the native select list options so that the plugin will find it and mark them as checked.
