### ISSUE TITLE
Insert data from mysql

### ISSUE THREAD

**Issue by tersosufix** [nobleclem/jQuery-MultiSelect#50]
Hello.
I need help, to show in multiselect input data from mysql table, I can't understand how.
where table structure include only three columns: num,name and group. Finaly i want to get in multiselect something like: num - name and would be awesome if it be included into groups from group column

**Comment by nobleclem** [comment]
Well getting data from mysql to the browser is outside the scope of this plugin.  This plugin just provides a easier to use interface for users in selecting multiple items from a <select> list.  If you are just trying to dynamically add/update data to an existing <select> list then you can follow the [example here](https://github.com/nobleclem/jQuery-MultiSelect/issues/26#issuecomment-219332904) for data structure the loadOptions method takes.
