### ISSUE TITLE
disabled option in dropdown

### ISSUE THREAD

**Issue by Wim74** [nobleclem/jQuery-MultiSelect#51]
Hello,

I'm using the multiselect code in my project. All is working fine, except one thing.

In my dropdown list I have items that are disabled. For example:
`<option value="7123" **disabled="disabled"**>Option TEXT</option>`

Is there a possibility to disable this with the plugin also?

Kind regards,

Wim

**Comment by nobleclem** [comment]
try
```
$('select[multiple]').multiselect({
    optionAttributes: ['disabled']
});
```

**Comment by Wim74** [comment]
Hello nobleclem,

That did the trick. Thank you very much for the tip.

Wim
