### ISSUE TITLE
load Remote data

### ISSUE THREAD

**Issue by sumit-sharma** [nobleclem/jQuery-MultiSelect#54]
How to add remote data ?

**Comment by nobleclem** [comment]
In the [README](https://github.com/nobleclem/jQuery-MultiSelect/blob/master/README.md) are some usage examples.  The last example is how to load data.  If you need to add group data then you should be able to follow the example in this [issue](https://github.com/nobleclem/jQuery-MultiSelect/issues/26#issuecomment-219332904).
