### ISSUE TITLE
Placement of .ms-options

### ISSUE THREAD

**Issue by warudin** [nobleclem/jQuery-MultiSelect#58]
Hi there,

Firstly: thanks for providing jQuery Multiselect!

I have one question about it: is it possible to place the .ms-options window _above_ the button, instead of below it? When the element is near the bottom of a page it will stretch out the page. In this case it would maybe be better if the .ms-options would be above the button.

Thanks in advance!

**Comment by nobleclem** [comment]
Should be able to accomplish this by changing the absolute positioning of the ms-option element.

The css should give you a quick start but additional adjustments will probably be necessary.
```bottom: 0;```

Its not a very common way of displaying dropdowns.  So your users might be a little jarred by doing this.  Might be easier for your users to just pad out the bottom so that the menu has room to fit.

**Comment by warudin** [comment]
For user experience it might not be optimal if a dropdown is placed above the button, but a page that stretches beneath it's own content isn't looking nice either. ;)

Thanks for your answer anyhow, I will fix this using plain CSS.

**Comment by nobleclem** [comment]
Well for a form its not unusual to have a select menu hide other items on the page including a button.  The action the user is trying to perform is selecting options from the list.  Once they are done it will close then items will be available again.  Also bootstrap has menus that drop down/up not select lists as far as I see.

Good luck!

**Comment by warudin** [comment]
Hi nobleclem,

It's no problem that the dropdown is temporarily above other buttons, this just happens in forms. What I mean is that the dropdown can sometimes be display partly outside of the body of the website. In this case I'd rather want it to be above the button (I mean the box to open the dropdown) instead of below.

In the meantime I've fixed this with an extra class and some CSS.
