### ISSUE TITLE
Select all taking very long

### ISSUE THREAD

**Issue by atlanticstarr1** [nobleclem/jQuery-MultiSelect#59]
Select all is taking a very long time to finish when we are trying to select 700 options at once. Any suggestions ?

**Comment by nobleclem** [comment]
Not off hand.  I would need to see if there was a way to optimize the function [here](https://github.com/nobleclem/jQuery-MultiSelect/blob/master/jquery.multiselect.js#L291) that makes that work.  Never dealt with 700 items in a select list.  I would say that a users computer will affect the speed of the operation.

**Comment by nobleclem** [comment]
Ran a test with 700 items and it took almost 3 seconds to select all.  I was able to shave it down to 1.1 = 1.3 seconds with Version 2.3.1.  Not sure I can make it any faster without potentially compromising features.  Hope that helps.

**Comment by atlanticstarr1** [comment]
Great!! works much better now. Thanks for the quick reply and fix.
