### ISSUE TITLE
Using loadOptions to dynamically set columns

### ISSUE THREAD

**Issue by atlanticstarr1** [nobleclem/jQuery-MultiSelect#61]
Can you show an example of using 'loadOptions' to dynamically set the columns of existing select lists when the 'onOptionClick' event is fired ? e.g. I have 2 cascading select lists. The user makes a selection in the 1st select list, and based on the number of results returned, i want to dynamically set the number of columns in the 2nd select list. So if the number of results is < 10, i want 1 column. If its > 10 i want 3 columns.

Thanks.

**Comment by nobleclem** [comment]
Added a way to change the plugins settings after you have already initialized it.  After you execute the `loadOptions` you can change the settings using something like `$('select[multiple]').multiselect( 'settings', { columns: 2 });`.  This will reload the multiselect list with the updated plugin options passed.
