### ISSUE TITLE
Automatically resize columns on screen resize

### ISSUE THREAD

**Issue by atlanticstarr1** [nobleclem/jQuery-MultiSelect#62]
Is there a way to automatically resize/recreate the columns when the screen size changes ?

**Comment by nobleclem** [comment]
The columns should resize automatically.  For most browsers the columns are created [using css](https://github.com/nobleclem/jQuery-MultiSelect/blob/master/jquery.multiselect.js#L576) on the generated UL that contains the options.  For IE browsers less than version 10 the columns are set [using a width percentage](https://github.com/nobleclem/jQuery-MultiSelect/blob/master/jquery.multiselect.js#L605).
