### ISSUE TITLE
Disabled Multiselect

### ISSUE THREAD

**Issue by HenkvandenBosch** [nobleclem/jQuery-MultiSelect#63]
When i have a disabled multiselect and use this plugin the select can still be changed.

**Comment by HenkvandenBosch** [comment]
base version: 2.3.3
the workaround i made in the js file:
starting on line 114:
`load: function () {
            var instance = this;
            var addItem = "";
            if ($(this.element).is("[disabled]")) {
                addItem = "disabled=\"disabled\"";
            }

            // make sure this is a select list and not loaded
            if ((instance.element.nodeName != 'SELECT') || $(instance.element).hasClass('jqmsLoaded')) {
                return true;
            }

            // sanity check so we don't double load on a select element
            $(instance.element).addClass('jqmsLoaded').data('plugin_multiselect-instance', instance);

            // add option container
            $(instance.element).after('<div class="ms-options-wrap"><button ' + addItem + '>None Selected</button><div class="ms-options"><ul></ul></div></div>');`

addition in css file:
.ms-options-wrap > button[disabled] {
    background-color: #e5e9ed;
    color: graytext;
    opacity: 0.6;
    filter: alpha(opacity=60);
}

**Comment by nobleclem** [comment]
This would work where the select list is disabled during load but if you then dynamically make the list available the button would still be disabled.  I would need to work through some things for disabled functionality to work normally.  Maybe just checking on button click of the native select list has been disabled or not.  Would need to check if the list becomes disabled or not.
