### ISSUE TITLE
$('select[multiple]').multiselect('reload') needs to reset the select options.

### ISSUE THREAD

**Issue by YajneshRai** [nobleclem/jQuery-MultiSelect#65]
I'm trying to implement a functionality where, I click on a button which clears all the multiselect buttons. The multiselect needs to clear all the currently selected options and should show the placeholder and the initial options. But when I try with `$('select[multiple]').multiselect('reload')` it doesn't seem to be clearing the selection, where as when I try `$('select[multiple]').multiselect('unload')`  it completely deletes the widget. Please need some help with this.

**Comment by nobleclem** [comment]
I have added a new method that you can use.
`$('select[multiple]').multiselect( 'reset' );`

This will reset the element back to its default values and reload the plugin for that element.

**Comment by YajneshRai** [comment]
Great!! Works fine now. Thanks!

**Comment by mubashir773** [comment]
$('#id').val('').trigger('change');
this worked for me
