### ISSUE TITLE
Search is VERY SLOW on mobile

### ISSUE THREAD

**Issue by atlanticstarr1** [nobleclem/jQuery-MultiSelect#66]
Can we have search functionality fire after the user finishes typing search term instead of firing after every keystroke ? The reason is that searches almost hang in firefox and on mobile devices.

**Comment by nobleclem** [comment]
You can now do something like
```
$('select[multiple]').multiselect({
    searchOptions: {
        delay: 500
    }
});
```
To add a search delay between keystrokes.  Without adding a button to manually execute a search there is no real way to tell if someone is done typing.  So this will allow you to change the delay to suite your large select list.
