### ISSUE TITLE
Checkbox Just Selecting not sorting values

### ISSUE THREAD

**Issue by princebhalani143** [nobleclem/jQuery-MultiSelect#69]
I am using third party JSON data on my WordPress website and code is coming as below.

```
<div class="facilities">
   <span class="label">Facilities</span>
   <span class="input">
      <select>
         <option value="">--- All ---</option>
         <option value="39946">Facility 01</option>
         <option value="39945">Facility 02</option>
      </select>
   </span>
</div>
```

I am converting above code in multiple select value using below line after DOM ready

Code 1: `$('.facilities').find('select').attr('multiple', true);`

After that I am using code as below to supply checkbox in to the list.

Code 2: ` $('.facilities').find('select').multiselect();`

It's converting code into checkbox but when I am using **Code 1** I am able to select multiple value using Ctrl+click and it's also sorting result value as well.

When I am supplying **Code 2** it's hiding code 1 changes and using Code 2 checkbox list, When selecting checkbox it's working and selecting value from Code 1 section but not showing any changes in my result.

Final Code Output as below.

```
<div class="facilities">
   <span class="label">Facilities</span>
   <span class="input">
      <select multiple="multiple" class="jqmsLoaded" style="display: none;">
         <option value="">--- All ---</option>
         <option value="39946">Facility 01</option>
         <option value="39945">Facility 02</option>
      </select>
      <div class="ms-options-wrap" style="position: relative;">
         <button>--- All ---</button>
         <div class="ms-options" style="min-height: 200px; overflow: auto; display: none; max-height: 200px;">
            <ul style="column-count: 1; column-gap: 0px;">
               <li class="default selected"><label for="ms-opt-1" style="padding-left: 80px;"><input type="checkbox" value="" title="--- All ---" id="ms-opt-1">--- All ---</label></li>
               <li class=""><label for="ms-opt-2" style="padding-left: 80px;"><input type="checkbox" value="39946" title="Facility 01" id="ms-opt-2">Facility 01</label></li>
               <li class=""><label for="ms-opt-3" style="padding-left: 80px;"><input type="checkbox" value="39945" title="Facility 02" id="ms-opt-3">Facility 02</label></li>
            </ul>
         </div>
      </div>
   </span>
</div>
```

Can you please guide me how I can implement code where user can select multiple checkbox in dropdown?

I have no access on third party data.

**Comment by nobleclem** [comment]
I am not sure what the problem is?  From the code samples provided it looks like everything is working as intended.  I even replicated the logic and everything seems to be working as expected.  The <select> element should be hidden once the plugin is loaded.  The plugin utilizes it to store the selected values so that it doesn't mess with form submission processes.  As far as I know you can't actually add a checkbox within a <select> element.  So the additional markup added after the <select> element is there to mimic the dropdown but with the intended functionality of the plugin.

Let me know if I am not understanding your issue correctly.
