### ISSUE TITLE
Question about getting Values

### ISSUE THREAD

**Issue by BlackBeanChicken** [nobleclem/jQuery-MultiSelect#71]
Help please :)   How do I "get/retrieve" the selected checkbox values from the MultiSelect control in JQuery/Javascript?   The example html in the zip is posting the Html values.  I need to grab the selected values from the MultiSelect control so I can update some JSON data..  Thanks in advance and sorry if this is the wrong place to ask a question.

**Comment by nobleclem** [comment]
The plugin selects and deselects items from the original list and to get the selected values via javascript just get them like a normal select list.
```$('select[multiple]').val();```

**Comment by BlackBeanChicken** [comment]
Maybe i'm misunderstand then how this control works.  Ummm, what I am looking for is the array of values that are selected by the options/checkboxes.  I seem to be getting a single string

**Comment by BlackBeanChicken** [comment]
Sorry never mind.  My bad, I figured it out what I did wrong. I did not have the keyword "multiple" in my html.  As I thought that was just used for the JQuery selector.
