### ISSUE TITLE
When clicking 'select all' while a search string is entered all items in the category are selected

### ISSUE THREAD

**Issue by JochenJung** [nobleclem/jQuery-MultiSelect#77]
Instead I would expect that only those items are selected that are currently visible because of the search string.

Steps to reproduce:
1) Open https://springstubbe.us/projects/demos/jquery-multiselect/
2) In the 'BASIC 3 COLUMN JQUERY MULTISELECT LIST' example type 'al' in the search box
3) Click 'select all'
4) Not only 'Alaska' and 'California' are selected but all other states as well.

**Comment by nobleclem** [comment]
That was a bug that had been previously fixed.  I have updated the plugin version on the demo.
