### ISSUE TITLE
jQuery validation VERY slow

### ISSUE THREAD

**Issue by atlanticstarr1** [nobleclem/jQuery-MultiSelect#78]
When the multiselect control is used to render a few hundred options, jQuery or Kendo validation is VERY slow. When said options are used with the native HTML select list, the validations are very fast. Any ideas ?

**Comment by nobleclem** [comment]
I am not sure what those validation methods are doing.  I do know that there is a checkbox created for everyone of your 700+ items (IIRC) in your list.  Its possible that this plugin might not be for you with a select list of your size and your requirements.  Maybe those validation methods are having to look at each one of the checkboxes for validations to be performed.

As far as Kendo validation it looks like that is a paid software.  So thats not something I am going to be able to debug properly.  You could try and remove the checkbox I add in and then see if the validation still takes a while.  Doing this will break how the plugin works but at least you can test that theory.

Alternatively you could write your own more efficient validation.  There are many ways to handle this but I am not sure any reasonable changes to the this plugin are going to solve your problem.  You could try and customize the plugin to handle your speed issues related to validation as well.
