### ISSUE TITLE
Columns Problem

### ISSUE THREAD

**Issue by messset** [nobleclem/jQuery-MultiSelect#79]
Whether I try
$('select[multiple]').multiselect({columns: 4,texts: {placeholder: 'Select options'}});
or 
$('select[multiple]').multiselect('settings', { columns: 2 });
,it always show the options with single column.

I can't find what's wrong...
Thanks!

**Comment by messset** [comment]
Oh , it's caused by jquery version.
Thank you!

**Comment by nobleclem** [comment]
Out of curiosity, what version were you using?

**Comment by messset** [comment]
I used jquery-1.8.2 originally.
