### ISSUE TITLE
Conflict with Mootools

### ISSUE THREAD

**Issue by Hectic** [nobleclem/jQuery-MultiSelect#8]
Hi Nobleclem,

I'm going to make this brief as I'm under some time constraints. Thank you for developing such a fabulous plugin. 

When I run the plugin on a webpage with both jQuery and Mootools installed the selection dropdown options gets messed up like so: 

![multiselect](https://cloud.githubusercontent.com/assets/2158169/12981064/0c5cc3d0-d0d7-11e5-8721-30c11547360d.png)

Note: I'm using jQuery no conflict. The solution was to change line 255 from:

`var groupOptions = [];`
to 
`var groupOptions = {};`

**Comment by nobleclem** [comment]
I have merged @domhnallw fix and hopefully that resolves your issue.  Version 2.0.1.
