### ISSUE TITLE
How to set default value?

### ISSUE THREAD

**Issue by parthustad** [nobleclem/jQuery-MultiSelect#81]
I am not able to set defualt value

**Comment by nobleclem** [comment]
You set it like any normal select list.  It will pickup the selected value and transfer it to the plugins UI.

The plugin inspects the native select list for values, attributes, and selections (default) and then builds its own UI as seen in the demos and hides the native select list.

**Comment by parthustad** [comment]
but how can i set value using jquery or javasccript?

**Comment by vimalvaghasiya** [comment]
I can not set the default selected values checked at the time of update.
Please put something thats why we can set the default selected values.

**Comment by nobleclem** [comment]
@vimalvaghasiya This has already been answered in this issue #81 as well as #82, #121 the README file as well as the [demo](https://springstubbe.us/projects/jquery-multiselect/) page See Examples:
- BASIC 3 COLUMN
- DYNAMICALLY POPULATE LIST
- DYNAMICALLY POPULATE LIST WITH OPTGROUPS

If those don't answer you question of how to default values then you will need to provide a more clear explanation with examples of what you are trying to do.
