### ISSUE TITLE
Checkbox not refreshing in jquery

### ISSUE THREAD

**Issue by m2vd** [nobleclem/jQuery-MultiSelect#83]
I am facing an issue as below.

I have two drop-down, first one is single drop down select, second one is multi select drop-down checkbox. Second one shows the result based on the first drop-down value.

While select the first drop-down, I get the values for second drop-down to show(Values Show in Inspect element) but not in drop down.

Please find the below code for further reference.

```
abc.html

<select  name="list_usergroup[]" multiple id="list_usergroup" >
<option value=""> Select User Group </option>                   
</select>
```

```
mg.js

org_uuid = $('#list_organization').val();
        $.ajax({
        url: appGetSecureURL("/api/web/getorgug/" + org_uuid),
        type: "GET",
        dataType: "json",
        jsonpCallback: 'jsonCallback',
        beforeSend : function(){
            loaderOn();
        },
        success: function(data) {

            // Display Usergroups
            if (0 == data.ug_total) {
                $("#list_usergroup").html('<option value="">No Usergroup.</option>');
            }
            else {
                $("#list_usergroup").html("");
                $("#list_usergroup").html('<option value="">Select Usergroup</option>');
                for (rowData in data.usergroups) 
                {
                    var optionData = '<option data = "'+ data.usergroups[rowData] +'" value="'+ rowData+'">' + data.usergroups[rowData]+'</option>';
                    $('#list_usergroup').val("");
                    $('#list_usergroup').multiselect('refresh');
                    $('#list_usergroup').multiselect('reset');
                    $("#list_usergroup").append(optionData);
                }

                //$('#list_usergroup').multiselect('reset');
                $("#list_usergroup").multiselect({
                            columns: 1,
                            placeholder: 'Select Usergroups',
                            search: true,
                            selectAll: true,
                            onLoad: function() {

                            }
                    });
                $("#list_usergroup").val(Value);
            }
            loaderOff();            
        },
        error: function(data, b, c) {
            appLog.debug("Display Usergroup error Status  " + data.status + ": " + data.statusText)
        }
    })
```
Thanks in advance.

**Comment by nobleclem** [comment]
So a couple things I see.

1. within your "for" loop you are issuing a refresh and reset.  refresh doesn't exist as a callable method.  Also you should really need to call a reset each time you add a option in the loop.
2. I am assuming that the #list_usergroup element has already been initialized by the multiselect plugin before this ajax call happens.  So if thats the case then you also shouldn't need to try and reinitialize it after the for loop.

So what I would do is initialize the #list_usergroup on pageload and then add the options in the ajax call.  You can either do it the way you are doing modifying the select element option directly OR you can use the multiselect "loadOptions" method to add them and it will add the option elements to the select list.

If you do it your way then after you have added the data to the select list you can call the following method: `$('#list_usergroup').multiselect('reload')` to have it refresh the multiselect list interface.

**Comment by m2vd** [comment]
Thanks for your support. it's helpful for me.
