### ISSUE TITLE
need custom select all option

### ISSUE THREAD

**Issue by hemanand** [nobleclem/jQuery-MultiSelect#85]
currently select all href link only generated our plugin.. but we need to configure checkbox with select all feature. So simply i need <checkbox> before "select all" for toggling selection.

Kindly let me know asap.

**Comment by nobleclem** [comment]
I don't understand what you are asking for.

**Comment by Sachelis** [comment]
I had to read this repeatedly, too. FWIW, I think he wants the "select all" option be displayed with a checkbox to its left so it looks like the other items in the list, rather than displaying it as a hyperlink.
