### ISSUE TITLE
Page unresponsive when record > 1000

### ISSUE THREAD

**Issue by shahzadthathal** [nobleclem/jQuery-MultiSelect#87]
Hi,

The whole page become unresponsive when records are greater than 1000, please help.

Thanks

**Comment by nobleclem** [comment]
Currently the plugin starts having performance issues at 400+ items.  If you want to use it I suggest finding ways to limit the number of items in the list.

**Comment by shahzadthathal** [comment]
Thank you for your reply.

Is it possible when scrolling down the list then load records from the database?

**Comment by nobleclem** [comment]
FYI,

I just tested this with 1100 items and not having any significant slowness issues.  Maybe another plugin or bit of code is causing the problem with the large number of items?
