### ISSUE TITLE
Performance Inquiry

### ISSUE THREAD

**Issue by ronniers** [nobleclem/jQuery-MultiSelect#89]
Have you tested the performance when the items is 8000?
Actually, we are planning to change 2 dropdowns into multiselect dropdowns but we are curious with the performance when we have many items.

Dropdown 1 contains around 8000 items. Dropdown 2 contains around 1000 items.

Thanks

**Comment by duduric** [comment]
Not very good, I just tested a dropdown with around 900 items and it freezes for some seconds when you open it. Maybe having a limit of items visible at once paired with the search box will improve, but this is not currently available and will need to be coded in.

**Comment by nobleclem** [comment]
I am in progress on some speed improvements.  I am not sure it will be as fast as you want but in a test of 8000 items the initialization goes from 13 seconds to 1.5 seconds.  Also trying to deal with some select all, open/close speed optimizations as well.  It's possible this might be a multi-staged release but we will see what tomorrow brings.

**Comment by ronniers** [comment]
Thank you for your feedbacks.
I was considering the suggestion of limiting the number of items and combining it with a search box. But if the speed would be improved from 13 seconds to 1.5 seconds will be great.

**Comment by nobleclem** [comment]
just committed 2.3.10 which has a first round of improvements.  Select all is NOT recommended for large lists.  I need to rework the select all logic to be faster.  I still want to figure out if there is a way to speed up the show/hide of the options, as well as see if I can speed up the page loading even more.  I need to do some more profiling but I am going to focus more on the select all for now.

**Comment by nobleclem** [comment]
just committed 2.3.11.  This should complete the speed improvements.   This version brings enhancements to the show/hide of the dropdown, select all speed increase, as well as slight speed increases to page load.  Your mileage may vary depending on what else you have going on the page as well as browser and computer specs.
