### ISSUE TITLE
Updating selectedOptions displayed text doesn't work with selectAll

### ISSUE THREAD

**Issue by tamarayee** [nobleclem/jQuery-MultiSelect#92]
The displayed selectedOptions doesn't update when "select all" and "unselect all" (available when selectAll is true) are clicked. I've tried it in Chrome 58.0.3029.110 (64-bit) and IE 11.296.15063.0 (update version 11.0.42) on Windows 10.

In addition to the displayed text, I think it's actually keep the previous selections in code. When I use "select all", it's not including all choices in the form post.

**Comment by tamarayee** [comment]
Got the version you use on https://springstubbe.us/projects/demos/jquery-multiselect/, and it works fine.

**Comment by nobleclem** [comment]
2.3.12 now fixes this bug.

**Comment by tamarayee** [comment]
Thanks!
